[envs.lint]
detached = true
dependencies = ["pre-commit"]

[envs.lint.env-vars]
SKIP = "no-commit-to-branch"

[envs.lint.scripts]
lint = "pre-commit run -a -v"

[envs.test.env-vars]
DJANGO_SETTINGS_MODULE = "tests.settings"

[envs.test.scripts]
test = "python runtests.py"

[envs.test.overrides]
matrix.django.dependencies = [
    { value = "django>=2.2,<4.0", if = ["3.2"] },
    { value = "django>=4.0,<4.1", if = ["4.0"] },
    { value = "django>=4.1,<4.2", if = ["4.1"] },
    { value = "django>=4.2,<5.0", if = ["4.2"] },
]

[[envs.test.matrix]]
python = ["3.8", "3.9"]
django = ["3.2", "4.0", "4.1", "4.2"]

[[envs.test.matrix]]
python = ["3.10"]
django = ["3.2", "4.0", "4.1", "4.2"]

[[envs.test.matrix]]
python = ["3.11"]
django = ["4.1", "4.2"]
